### PR TITLE
Save icon for cuesheet

### PR DESCRIPTION
**Pull request by alex-Arc**
from this
image

to this
image

### CODE REVIEW

**Comment by cpvalente** [comment]
hey @alex-Arc , we seem to have some issues with the commits here
As for the change, I think the save icon on its own does not explain what is happening, how about adding icon and keeping the "export" text?

**Comment by alex-Arc** [comment]
I was thinking that since it opens the same modal as this button
image
it should just be the same?

**Comment by cpvalente** [comment]
Hi @alex-Arc , can we close this for now? lets revisit once we had some time to think through UI properly

**Comment by alex-Arc** [comment]
Sounds good

**Pull request closed without merging**
