### PR TITLE
feat: google sheets

### PR DESCRIPTION
**Pull request by hrueger**
Hi @cpvalente,
I finally found some time to push what I was able to get working regarding the authentication.
You need to create your own google cloud project, because mine is set to test and I don't know your gmail address to add you as a test user. But setting the project up is easy, if I remember everything ;-)
- Go to https://console.cloud.google.com and create a project
- activate the google sheets api
- go to OAuth Consent Screen and setup your application (for now, test is probably fine). Add yourself as a testuser
- go to Credentials and create a new OAuth 2.0 Client ID
    - use type webapplication
    - add the following authorized js origins:
        - http://localhost:3001
        - http://localhost:3000
        - http://localhost:4001
        - http://localhost
    - copy the client id and change the value in [apps/client/src/features/modals/settings-modal/SettingsModal.tsx](https://github.com/cpvalente/ontime/compare/master...hrueger:google-sheets?expand=1#diff-82e144a5530837c06c249dba43315be8dab88e11a32e92d70fb0700e3bbf966a)

Currently, there's no import logic, we just log the document title to make sure we can talk to the API.

ToDo:
- [x] Move Client ID to a .env variable for developing with own cloud projects and setup GitHub Actions + Secrets to add that to the build
- [ ] Make the Sheet ID configurable in the modal (I just copied a different settings tab page)
- [ ] Maybe we should make the sheet selectable? With the drive api, we could get a list of recently used sheets ;-) Problably something for a second step, though.
- [ ] Add actual import / export logic (maybe like with the excel files? I believe I saw a pre-release there) with a Sync button
- [ ] Automatically refresh the access_token via the refresh_token
- [x] Create an external login page hosted with GitHub pages
    - then, we can get logins from outside the Electron app working
    - Hosting the button on GitHub Pages means we have a fixed js origin.
    - When the button returns the access token and refresh token, we could either do a clientside js redirect back to ontime (url specified via query params) - however, this is probably insecure since we cannot verify that we're redirecting to ontime and not to somewhere else.
    - The more secure alternative would be to let the user copy the json structure (maybe encoded as base64 or something) and paste it in ontime. Then, we're sure that the user is doing that on purpose. However, it is not as convenient. 
    - Or we can ask the user if he is sure that his ontime is running at [ip].

What do you think? Do you have some time to assist?

### CODE REVIEW

**Comment by cpvalente** [comment]
Hi @hrueger, really great work. I am very grateful for all your contributions so far.

As you noticed, I have been working from ontime's side on making this possible.

The first step is to create an import map #506, this creates necessary UI for dynamic import and backend solutions for import review
Once this is in production we can use it in this feature too.

I am trying to move forward with some of the new features, but will do my best to help here.
How can I help? is there a part of this flow we need me to get to ASAP?

What are the details of the login page? maybe that is something we can sandbox together and I will make a repo once we are happy with the code?

**Comment by hrueger** [comment]
Hi @cpvalente,
thanks.

> As you noticed, I have been working from ontime's side on making this possible.

Yes, that is great.

> How can I help?

if you have some time, you could

- **Make the Sheet ID configurable in the modal**
    I'm not a react developer and therefore not familiar with hooks and form handling. Last time I worked on this, it took me forever. I believe you're much faster ;-) For now, we only need a better style for the login button as well as an input field for the sheet id. The value of the Enable Sync switch as well as the sheet id should be saved in the rundown file. Maybe the switch should disable the button and the input field if it is off. We then need the data (for now) [here](https://github.com/cpvalente/ontime/pull/520/files#diff-4feb684208c87cd80f4d4992dab168483573a25ca8ca378937f882758fda9d29R280).
- **Add actual import / export logic**
    I'm not very familiar with the excel import logic nor with the data storage. We should add a sync button which then (on the server) queries the sheet data (like in the [example here](https://github.com/cpvalente/ontime/pull/520/files#diff-4feb684208c87cd80f4d4992dab168483573a25ca8ca378937f882758fda9d29R279-R281)) (see library [docs](https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=googlespreadsheetworksheet)).


I can work on the authorization page for non-electron users. I just noticed that you're not hosting the ontime homepage on GitHub pages (or am I wrong?). However, I think that this would be good for the auth page because of transparency for end users.
We don't need a new repository for this, we can just add it to the gh-pages branch. Then, you just need to enable Pages in the settings.

By the way, a friend of mine wants this working on the 22nd ;-) I suggest we just see how far we can get.

Thanks for your support!

**Comment by cpvalente** [comment]
> Make the Sheet ID configurable in the modal

Sure, I will add this once the current excel work is merged.
For now you could add a field in the json project file and change it manually

> Add actual import / export logic


I think this will take some time to get right. There are several things to consider and we need to make sure that such updates cause the least disturbance to the running of the services as possible.

Do you happen to know if we get a changelist from google or simply the new spreadsheet data?

Either way, I will make sure to work on it and lay out foundations as part of the current excel work.


> I can work on the authorization page for non-electron users. I just noticed that you're not hosting the ontime homepage on GitHub pages (or am I wrong?). However, I think that this would be good for the auth page because of transparency for end users.
> We don't need a new repository for this, we can just add it to the gh-pages branch. Then, you just need to enable Pages in the settings.

You are correct, the homepage is a separate repository and is hosted in vercel.
I am unsure that adding this to the repo is a good idea, the existence of this piece of code is a work-around for a third party integration. I see all advantages in keeping this as isolated as possible.  Why do you think it is better for transparency than a separate repo?


> By the way, a friend of mine wants this working on the 22nd ;-) I suggest we just see how far we can get.


Unfortunately that might be too optimistic of a target, at least for ontime.
We have a few moving targets right now, including code dependencies for the application of the google sheets integration (excel import). All contributors work in Ontime in their spare time, including the testers reviewing new releases. It is tricky for us to maintain hard deadlines on features, especially such short ones

I can try and help give you what you need so that you might be able to go further in your own fork

**Comment by hrueger** [comment]
> > Make the Sheet ID configurable in the modal
> 
> Sure, I will add this once the current excel work is merged. For now you could add a field in the json project file and change it manually

That's a good idea, will do. Thanks

> > Add actual import / export logic
> 
> I think this will take some time to get right. There are several things to consider and we need to make sure that such updates cause the least disturbance to the running of the services as possible.

I agree, that makes sense.

> Do you happen to know if we get a changelist from google or simply the new spreadsheet data?

I don't think so. We could save a copy (e.g. as json) somewhere and calculate our own diff, although I don't know if that makes sense.

> Either way, I will make sure to work on it and lay out foundations as part of the current excel work.

Sounds great!

> > I can work on the authorization page for non-electron users. I just noticed that you're not hosting the ontime homepage on GitHub pages (or am I wrong?). However, I think that this would be good for the auth page because of transparency for end users.
> > We don't need a new repository for this, we can just add it to the gh-pages branch. Then, you just need to enable Pages in the settings.
> 
> You are correct, the homepage is a separate repository and is hosted in vercel. I am unsure that adding this to the repo is a good idea, the existence of this piece of code is a work-around for a third party integration. I see all advantages in keeping this as isolated as possible. Why do you think it is better for transparency than a separate repo?

Maybe I didn't express myself clearly. I meant I'd like this page to be open-source and be deployed by CI, so everyone can check that we're not doing anything with the access tokens (like sending them to third parties, etc)

Sure, we can put that in a separate repo if you want. It's super simple, I just published a demo. It's just one `index.html` file (currently in the `gp-pages` folder).

> > By the way, a friend of mine wants this working on the 22nd ;-) I suggest we just see how far we can get.
> 
> Unfortunately that might be too optimistic of a target, at least for ontime. We have a few moving targets right now, including code dependencies for the application of the google sheets integration (excel import). All contributors work in Ontime in their spare time, including the testers reviewing new releases. It is tricky for us to maintain hard deadlines on features, especially such short ones
> 
> I can try and help give you what you need so that you might be able to go further in your own fork

Oh, I didn't want to create stress in any case or impose deadlines. It was more of a joke ;-) cause I don't think we'll have it fully working and polished by then either.

**Comment by cpvalente** [comment]
Hahaha, no worries. I appreciate having your help and look forwards to start working on it

**Comment by cpvalente** [comment]
Hi @hrueger, I have created a separate repo to host the github pages.
We will likely need to improve the code and the documentation, but lets get it working first.

You should have received an invitation to be a collaborator.

I will continue moving the rest of the things along so we can merge the excel stuff, feel free to ping me if there is anything you need me to do 

Thank you again

**Comment by hrueger** [comment]
Thanks! The invitation worked. I'll probably move on with this on Sunday.

**Comment by hrueger** [comment]
Hi @cpvalente,
Quick question: after importing the sheet data [here](https://github.com/cpvalente/ontime/pull/520/files#diff-73c7d11ba5c4c95bba8767d22afc20f177646d2cfb57eb6bcf7c01176510e07bR124), how do I tell the UI to refresh? `sendRefetch()`only seems to be for external UIs?
Thanks in advance

**Comment by cpvalente** [comment]
> Hi @cpvalente,
> 
> Quick question: after importing the sheet data [here](https://github.com/cpvalente/ontime/pull/520/files#diff-73c7d11ba5c4c95bba8767d22afc20f177646d2cfb57eb6bcf7c01176510e07bR124), how do I tell the UI to refresh? `sendRefetch()`only seems to be for external UIs?
> 
> Thanks in advance


Hi, in the case of upload, we can invalidate the cache in react-query which triggers a refetch

See example here 

https://github.com/cpvalente/ontime/blob/master/apps/client/src/features/modals/upload-modal/UploadModal.tsx#L70

**Comment by hrueger** [comment]
Perfect, thanks!

**Comment by hrueger** [comment]
superseded by #579 🚀
@cpvalente that pr also makes https://github.com/cpvalente/ontime-gsheets-sync obsolete, if you want, you can archive that repository 👍

**Pull request closed without merging**
