### PR TITLE
address some issues in am/pm time parsing

### LINKED ISSUE #994: Smart Time entry doesn't seem to handle 12-hour time entries for hours ≥10 without a space
*Installation*: v3.0.3 via Docker (Synology NAS)

---

Times with "a", "am", "p", or "pm" exhibit some strange behavior. I think there is no smart time entry documentation on 12 hour times, but some things work and some things… don't.

 For example:
- `9a`, `9am`, `9 a`, `9 am`, `9p`, `9pm`, `9 p`, `9 pm` all parse as expected: `09:00:00` or `21:00:00`
- `10 a`, `10 am`, `10 p`, `10 pm` all parse as expected: `10:00:00` or `22:00:00`
- `10a`, `10am`, `10p`, `10pm` (no space) **do not parse**

### PR DESCRIPTION
**Pull request by jwetzell**
resolve some oddities with parsing am/pm times like 10am, 12:00pm, 12:00:00am, etc. 

closes #994

### CODE REVIEW

**Review by cpvalente — APPROVED** [review]

**Comment by cpvalente** [comment]
Thank you @jwetzell , changes look good. Good job navigating the logic 🍝

We will need a next step to generalise this logic for backend and frontend. Do you mind if I do it?

**Comment by jwetzell** [comment]
@cpvalente all yours! Are you going to want to do that in this branch or should I merge this and let you sort it out at a later time.

**Comment by cpvalente** [comment]
I think we should merge this.

All I need to do is to extract the logic and iron out potential mismatches to the backend implementation. I will ask for your review when it is done

**Comment by jwetzell** [comment]
sounds good!

**Pull request merged**
