### PR TITLE
wip: time to next

### LINKED ISSUE #160: Show the time to the next event
At times, we need to know how long until a certian event.  We would like onTime to calculate this automatically.  Inital thoughts are perhaps we could hover the mouse over the cue and this information could appear in a "tips" temporary window.

thanks !

### PR DESCRIPTION
**Pull request by cpvalente**
WIP

Closes #160 

image
image

### CODE REVIEW

**Comment by cpvalente** [comment]
Hi @alex-Arc , I have started working on this with the idea that we can show in the cuesheet, the time for every event start.

I realised then that we dont have a data source to show the time when a past event has started,
A work around for now is to not calculate this for events that are in the past.

I feel like the feature is confusing without the real start time data, and we are better off not releasing it until we get this
What do you think?

**Comment by alex-Arc** [comment]
I dose feel confusing the way it shows up in the cue sheet.
a popup might be less distracting?

**Comment by alex-Arc** [comment]
just did a quick test
moving the it from the cuesheet into the right-click menu of the rundown
it doesn't live update but maybe that is a good thing?
image

apps\client\src\features\rundown\event-block\EventBlock.tsx
```typescript
  const timer = useTimer();
  const [onContextMenu] = useContextMenu<HTMLDivElement>([
    { label: `Copy ID: ${eventId}`, icon: IoCopyOutline, onClick: () => copyToClipboard(eventId) },
    //....................
    {
      label: millisToDelayString(timeStart - timer.clock) ?? '',
      icon: IoTimeOutline,
      onClick: () => console.log('test'),
      isDisabled: true,
    },
  ]);

```

**Comment by alex-Arc** [comment]
> I am not particularly keen on adding the timer as a dependency to the context menu, we can workshop some other solutions

I can understand that :)

last night I felt that the wall of timers ticking down was very distracting, it is not to bad looking at it now with fresh eyes
but sill I don't know if it is good to have so many fields updating at once?

also a better name might be `Planed start`

**Comment by cpvalente** [comment]
> but sill I don't know if it is good to have so many fields updating at once?
> 

True. The problem to solve here is to provide a overview over how far a particular event is from starting. This wall of timers is likely what you would see in cue lab or grandMA.  

Would this make more sense in the operator where there are less things? 

Or perhaps we only show the time to the next element?

> also a better name might be `Planned start`
> 

Real start might need tweaking but Planned Start is incorrect since it should show the time to either 
a) the time an event will start 
b) the time behind for an event start (previous event running overtime)
c) the time the event has started 

This fields value should only be planned start if the event is in future and we are not having any delays

**Comment by je71175** [comment]
Hi all.  I agree a wall of timers would be distracting and creating pop ups are only useful for a quick look - not a countdown values when other things are happening in the show.  
As a thought, would it be possible to say have the duration field clickable - and have it toggle between the duration value and the countdown to this upcoming event  This way the user can select and choose to see which events display the countdown timer...
thanks Jason

**Comment by Punkerschaf** [comment]
Hey guys, I also would like to leave some various thoughts and this:

- Finding a name: My suggestion is `Log/Exp` Loggend/Expected. On past events it shows the logged time it startet, for future events the expected time to start based on current logging+durations.

- To limit the count of rendered times wouldn't it be the easiest to just have an option to render the next X events?

- In my opinion this is not a necessary information on the operator view. As an operator I rather need the time till I have to do something (to the next highlighted userfield on my view). But I understand this feature is a few steps in the future.

- On the cuesheet it could be helpful to show, that this is a calculated time and not editable in any way. Maybe to not draw the background box could be a small improvement, if we wan't to keep this in a separate column.

**Comment by cpvalente** [comment]
Parking this until we get the reporter going

**Pull request closed without merging**
