### PR TITLE
Feat: Editable table 

### PR DESCRIPTION
**Pull request by alex-Arc**
Trying out [tanstack table](https://tanstack.com/table/v8)

### CODE REVIEW

**Comment by cpvalente** [comment]
You can see how the cuesheet is done, it is already using tanstack table

**Comment by alex-Arc** [comment]
ag-grid seams easy to use so far, but it is a good deal bigger (787 kB vs 36.8 MB)

**Comment by cpvalente** [comment]
if we can do this with the tanstack table it is better.
If you could get it to a point where you can edit in table we can build the customisation from there.
In short, it would end up looking very much like the cuesheet

**Comment by alex-Arc** [comment]
this might be done at a later time

**Pull request closed without merging**
