### PR TITLE
Fix: Removed `updatedAt` from project list

### PR DESCRIPTION
**Pull request by arymoraes**

### CODE REVIEW

**Comment by cpvalente** [comment]
I believe the problem I observe is the opposite. The created at date is changed everything a file is modified.

Before we remove the dataset, we should understand the issue.

If we find that for some reason, we can't maintain the created at dataset, we should remove it completely, not just the presentation

**Comment by alex-Arc** [comment]
I think I found the reason
We use lowDb and they use steno to do the actual writing and steno uses always writes to a tmp file and then replaces the original, so there will never be any useful "created at" data available

https://github.com/typicode/lowdb/blob/6fc49ccb69666ad9159d1403514549a6af5fa8ef/src/adapters/node/TextFile.ts#L42

**Comment by alex-Arc** [comment]
We should either keep the updatedAt and remove createdAt

or alternatively manually add a createdAt filed to our json project file type

**Comment by cpvalente** [comment]
> We should either keep the updatedAt and remove createdAt
> 
> 
> 
> or alternatively manually add a createdAt filed to our json project file type

Agreed, if we can't maintain a meaningful dataset we should remove it.

If we get to a point where users find a lot of value in a createdAt we can look into persisting it solutions.

**Comment by arymoraes** [comment]
I kept the `updatedAt`, just not sure about `Last Used` as the column header

**Comment by cpvalente** [comment]
> I kept the `updatedAt`, just not sure about `Last Used` as the column header

if you think it should be renamed, it is ok with me

Remember to update the tests

**Comment by cpvalente** [comment]
Hi @arymoraes , is this ready to be reviewed?

**Comment by arymoraes** [comment]
> Hi @arymoraes , is this ready to be reviewed?

hey yes it is

**Review by alex-Arc — APPROVED** [review]

**Pull request merged**
